# Project information
site_name: Noordstreek wet- en regelgeving
site_author: Noordstreek
site_url: wetboek.noordstreek.nl

copyright: Copyright &copy; 2021 - 2022 Noordstreek

theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: img/noordstreek.png
  logo: img/noordstreek.png
  custom_dir: docs/overrides
  language: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
 # - Wetboek: wetboek.md
 # - Risicogebieden: risico-gebieden.md
 # - Douanegebieden: douanegebieden.md
 # - NOTAM: notam.md
 # - Belastingen: belastingen.md
 # - Regelement voor de rechtspraak: rechtspraak.md
  - Streamen op Noordstreek: streamen.md
 # - Offroad Voertuigen: offroadvoertuigen.md
 # - Kosten:
   # - Advocatuur: kosten/advocatuur.md
   # - Ambulance: kosten/ambulance.md
   # - ANWB: kosten/anwb.md
   # - Politie: kosten/politie.md
   # - Vliegschool: kosten/vliegschool.md
